export const screens = [
	{ name: '1', path: '/screens/1.jpg' },
	{ name: '2', path: '/screens/2.jpg' },
	{ name: '3', path: '/screens/3.jpg' },
	{ name: '4', path: '/screens/4.jpg' },
	{ name: '5', path: '/screens/5.jpg' },
	{ name: '6', path: '/screens/6.jpg' },
	{ name: '7', path: '/screens/7.jpg' },
	{ name: '8', path: '/screens/8.jpg' },
	{ name: '9', path: '/screens/9.jpg' },
	{ name: '10', path: '/screens/10.jpg' },
	{ name: '11', path: '/screens/11.jpg' },
	{ name: '12', path: '/screens/12.jpg' },
	{ name: '13', path: '/screens/13.jpg' },
	{ name: '14', path: '/screens/14.jpg' },
	{ name: '15', path: '/screens/15.jpg' },
	{ name: '16', path: '/screens/16.jpg' },
	{ name: '17', path: '/screens/17.jpg' },
	{ name: '18', path: '/screens/18.jpg' },
	{ name: '19', path: '/screens/19.jpg' },
	{ name: '20', path: '/screens/20.jpg' },
	{ name: '21', path: '/screens/21.jpg' },
	{ name: '22', path: '/screens/22.jpg' },
	{ name: '23', path: '/screens/23.jpg' },
	{ name: '24', path: '/screens/24.jpg' },
	{ name: '25', path: '/screens/25.jpg' },
	{ name: '26', path: '/screens/26.jpg' },
	{ name: '27', path: '/screens/27.jpg' },
	{ name: '28', path: '/screens/28.jpg' },
	{ name: '29', path: '/screens/29.jpg' },
	{ name: '30', path: '/screens/30.jpg' },
	{ name: '31', path: '/screens/31.jpg' },
	{ name: '32', path: '/screens/32.jpg' },
	{ name: '33', path: '/screens/33.jpg' },
	{ name: '34', path: '/screens/34.jpg' },
	{ name: '35', path: '/screens/35.jpg' },
	{ name: '36', path: '/screens/36.jpg' },
	{ name: '37', path: '/screens/37.jpg' },
	{ name: '38', path: '/screens/38.jpg' },
	{ name: '39', path: '/screens/39.jpg' },
	{ name: '40', path: '/screens/40.jpg' },
	{ name: '41', path: '/screens/41.jpg' },
	{ name: '42', path: '/screens/42.jpg' },
	{ name: '43', path: '/screens/43.jpg' },
	{ name: '44', path: '/screens/44.jpg' },
];

export const onboardImage = {
	name: 'on board image',
	path: '/images/git-hub-board.png'
}